name: deploying to aws s3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS S3
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config="bucket=rohit-luffy-portfolio-tfstate"

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Debug Terraform Outputs
        run: terraform output -json

      - name: Get API Gateway URL from Terraform Output
        run: |
          API_URL=$(terraform output -json | python3 -c "import sys,json; print(json.load(sys.stdin)['chat_api_url']['value'])")
          echo "Fetched API URL: $API_URL"
          echo "API_URL=$API_URL" >> $GITHUB_ENV

      - name: Inject API URL into script.js
        run: |
          sed -i "s|REPLACE_WITH_API_URL|${{ env.API_URL }}|g" script.js
          echo "Injected: ${{ env.API_URL }} into script.js"

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
            --exclude "*" \
            --include "*.html" \
            --include "*.css" \
            --include "*.js" \
            --delete